import { Button, Navbar, Container, Nav, Table } from 'react-bootstrap'
import Header from './head/header.js'


function shoebox_pro(props) {
    return (
        <>
            <Header></Header>
            <Container>
                <h3>슈박스 확률</h3>
                <Table bordered hover size='md'>
                    <thead>
                        <tr>
                            <th>운동화1</th>
                            <th>운동화2</th>
                            <th>커먼(%)</th>
                            <th>언커먼(%)</th>
                            <th>레어(%)</th>
                            <th>에픽(%)</th>
                            <th>레전더리(%)</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>커먼</td>
                            <td>커먼</td>
                            <td>100</td>
                            <td>0</td>
                            <td>0</td>
                            <td>0</td>
                            <td>0</td>
                        </tr>
                        <tr>
                            <td>커먼</td>
                            <td>언커먼</td>
                            <td>50</td>
                            <td>49</td>
                            <td>1</td>
                            <td>0</td>
                            <td>0</td>
                        </tr>
                        <tr>
                            <td>커먼</td>
                            <td>레어</td>
                            <td>50</td>
                            <td>0</td>
                            <td>49</td>
                            <td>0</td>
                            <td>0</td>
                        </tr>
                        <tr>
                            <td>커먼</td>
                            <td>에픽</td>
                            <td>50</td>
                            <td>0</td>
                            <td>0</td>
                            <td>49</td>
                            <td>1</td>
                        </tr>
                        <tr>
                            <td>커먼</td>
                            <td>레전더리</td>
                            <td>50</td>
                            <td>0</td>
                            <td>0</td>
                            <td>0</td>
                            <td>50</td>
                        </tr>
                        <tr>
                            <td>언커먼</td>
                            <td>언커먼</td>
                            <td>0</td>
                            <td>98</td>
                            <td>2</td>
                            <td>0</td>
                            <td>0</td>
                        </tr>
                        <tr>
                            <td>언커먼</td>
                            <td>레어</td>
                            <td>0</td>
                            <td>49</td>
                            <td>50</td>
                            <td>1</td>
                            <td>0</td>
                        </tr>
                        <tr>
                            <td>언커먼</td>
                            <td>에픽</td>
                            <td>0</td>
                            <td>49</td>
                            <td>1</td>
                            <td>49</td>
                            <td>1</td>
                        </tr>
                        <tr>
                            <td>언커먼</td>
                            <td>레전더리</td>
                            <td>0</td>
                            <td>49</td>
                            <td>1</td>
                            <td>0</td>
                            <td>50</td>
                        </tr>
                        <tr>
                            <td>레어</td>
                            <td>레어</td>
                            <td>0</td>
                            <td>0</td>
                            <td>98</td>
                            <td>0</td>
                            <td>50</td>
                        </tr>
                        <tr>
                            <td>레어</td>
                            <td>에픽</td>
                            <td>0</td>
                            <td>0</td>
                            <td>49</td>
                            <td>50</td>
                            <td>1</td>
                        </tr>
                        <tr>
                            <td>레어</td>
                            <td>레전더리</td>
                            <td>0</td>
                            <td>0</td>
                            <td>49</td>
                            <td>1</td>
                            <td>50</td>
                        </tr>
                        <tr>
                            <td>에픽</td>
                            <td>에픽</td>
                            <td>0</td>
                            <td>0</td>
                            <td>0</td>
                            <td>98</td>
                            <td>2</td>
                        </tr>
                        <tr>
                            <td>에픽</td>
                            <td>레전더리</td>
                            <td>0</td>
                            <td>0</td>
                            <td>0</td>
                            <td>49</td>
                            <td>51</td>
                        </tr>
                        <tr>
                            <td>레전더리</td>
                            <td>레전더리</td>
                            <td>0</td>
                            <td>0</td>
                            <td>0</td>
                            <td>0</td>
                            <td>100</td>
                        </tr>
                    </tbody>
                </Table>
                <h3>슈박스 드랍률</h3>
                <Table striped bordered hover size='md'>
                    <thead>
                        <tr>
                            <th>슈박스(퀄리티)</th>
                            <th>커먼(%)</th>
                            <th>언커먼(%)</th>
                            <th>레어(%)</th>
                            <th>에픽(%)</th>
                            <th>레전더리(%)</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>커먼</td>
                            <td>97</td>
                            <td>3</td>
                            <td>0</td>
                            <td>0</td>
                            <td>0</td>
                        </tr>
                        <tr>
                            <td>언커먼</td>
                            <td>25</td>
                            <td>73</td>
                            <td>2</td>
                            <td>0</td>
                            <td>0</td>
                        </tr>
                        <tr>
                            <td>레어</td>
                            <td>0</td>
                            <td>27</td>
                            <td>71</td>
                            <td>2</td>
                            <td>0</td>
                        </tr>
                        <tr>
                            <td>에픽</td>
                            <td>0</td>
                            <td>0</td>
                            <td>30</td>
                            <td>68</td>
                            <td>2</td>
                        </tr>
                        <tr>
                            <td>레전더리</td>
                            <td>0</td>
                            <td>0</td>
                            <td>0</td>
                            <td>35</td>
                            <td>65</td>
                        </tr>
                    </tbody>
                </Table>

                <h3>슈박스 운동화확률</h3>
                <Table striped bordered hover size='md'>
                    <thead>
                        <tr>
                            <th>운동화1</th>
                            <th>운동화2</th>
                            <th>워커(%)</th>
                            <th>조거(%)</th>
                            <th>러너(%)</th>
                            <th>트레(%)</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>워커</td>
                            <td>워커</td>
                            <td>85</td>
                            <td>6</td>
                            <td>6</td>
                            <td>3</td>
                        </tr>
                        <tr>
                            <td>워커</td>
                            <td>조거</td>
                            <td>45</td>
                            <td>45</td>
                            <td>7</td>
                            <td>3</td>
                        </tr>
                        <tr>
                            <td>워커</td>
                            <td>러너</td>
                            <td>45</td>
                            <td>7</td>
                            <td>45</td>
                            <td>3</td>
                        </tr>
                        <tr>
                            <td>워커</td>
                            <td>트레</td>
                            <td>80</td>
                            <td>6</td>
                            <td>6</td>
                            <td>8</td>
                        </tr>
                        <tr>
                            <td>조거</td>
                            <td>러너</td>
                            <td>7</td>
                            <td>45</td>
                            <td>45</td>
                            <td>3</td>
                        </tr>
                        <tr>
                            <td>조거</td>
                            <td>트레</td>
                            <td>6</td>
                            <td>80</td>
                            <td>6</td>
                            <td>8</td>
                        </tr>
                        <tr>
                            <td>러너</td>
                            <td>러너</td>
                            <td>6</td>
                            <td>6</td>
                            <td>85</td>
                            <td>3</td>
                        </tr>
                        <tr>
                            <td>러너</td>
                            <td>트레</td>
                            <td>6</td>
                            <td>6</td>
                            <td>80</td>
                            <td>8</td>
                        </tr>
                        <tr>
                            <td>트레</td>
                            <td>트레</td>
                            <td>25</td>
                            <td>25</td>
                            <td>25</td>
                            <td>25</td>
                        </tr>
                    </tbody>
                </Table>

            </Container>
        </>
    );

}


export default shoebox_pro;